### ISSUE TITLE
Coderetreat on October 22th (GDCR16)

### ISSUE THREAD

**Issue by codecop** [CodingDojoVie/sessions#15]
It is not too late to organize an event for GDCR 2016! Please register using the following form:
http://goo.gl/forms/Px0ytk6ZS7ZQAdew1

For more context, please take a look at the the following coderetreat blog post:
http://coderetreat.org/profiles/blogs/how-to-participate-in-the-global-day-of-coderetreat-2016

Just like last year, GDCR is sponsoring CoderDojo, a worldwide, volunteer driven programming club for kids. The video says it all:
https://www.youtube.com/watch?v=z_gcHGa8J1E

**Comment by dertseha** [comment]
As discussed: We at FRQ would be happy to host it again (With my personal note: It does not have to be always FRQ).

Apart from that, we need at least one facilitator, either way.

So, volunteers, proponents or other prospects?

**Comment by dertseha** [comment]
I just thought it would be good to have a deadline by which things should be clear, to have a go/no-go:
* Who's hosting (Currently: default fallback FRQ)
* Who's facilitating
If we don't have answers by that deadline, it won't happen. I propose the 31st of August.

Also paging @mlem and @ernst-fastl for input.

**Comment by mlem** [comment]
Hello,

I think, willhaben has not enough capacity to host a code retreat. There
are few big rooms but they can hold max 15 persons :).

If you can't find a facilitator, see me as fallback. It's harder then I
thought, but I could try it again. In the end it's fun to do.

Cheers,
martin

Am 17.08.2016 22:52 schrieb "Christian Haas" <notifications@github.com>:

**Comment by codecop** [comment]
Traditionally I plan to be away for GDCR. Seems like I will be on the ferry between Stockholm and Helsinki this time. Sorry I can not help with facilitation.

**Comment by ernst-fastl** [comment]
We cannot host, but I am happy to facilitate.

**Comment by dertseha** [comment]
Thank you for your quick responses.
Seems like we stick with FRQ as the host. As for facilitation, we could:
* Share it between us (Martin, Ernst and myself) and
* make a call for volunteers for single sessions at the registration.

Though, I don't know much you two (Martin, Ernst) would want to join in on coding or would otherwise feel bored for a session, while someone else takes over.

I will ask at FRQ next week.

**Comment by ernst-fastl** [comment]
@dertseha: thanks for offering to host again

Regarding facilitation I am open for sharing and volunteers. It would be nice to do some coding for a session or two. That does not sound boring :-)

**Comment by dertseha** [comment]
Well, I did ask and was not met with immediate enthusiasm. For one, because we had said that the previous one was to be held at FRQ because "the GDCR would be hosted somewhere else anyway", and second because the attendance from our own people is minimal.

Still, the request will be forwarded to the head of development (who'll ultimately pay for the whole thing). A further idea was also that I should ask at SoCraTes whether there would be any external facilitators willing to come. (Payment of such an import would require more attendance from our company as well, so that's a vague point.)

Thinking into another direction: How many people are we expecting? From the last 26 guests we had, we can deduct 6 (?) people from the dev-gang, who wouldn't be there. I also doubt our subsidiary from Germany would send again two, especially if they have a GDCR in their own city. So we're down at 16, which could be hosted by @mlem . (Just thinking out loud here, brainstorming.)

Finally, what we also discussed: If we, the only immediate potential facilitators, say "meh", and our current host is also rather in a state of "meh" (so far)... Perhaps this is a sign that we skip a year?
(Note: The CodingDojoVie last week had three participants, with only one external :/ )

Difficult.

**Comment by codecop** [comment]
Sadly the enthusiasm for CR has been declining in Vienna ever since. Obviously a single company does not want and should not host all the CR in Vienna - or maybe should if it wants to grow a name for it, but it is not expected. So aiming for a smaller event might make a difference, having a small event which is sold out could be cool. Also maybe places like Stockwerk would host for up to 40 ppl but I think that would be very crowded then.

So the question is: Do we (as CodingDojoVie) want to have a Coderetreat for ourselves? All else is following.

**Comment by dertseha** [comment]
I like to participate on such retreats. Then again, there was one already this year and there is a (slight) chance that similar mentality is expected on the two SoCraTes conferences I'll be these months (Germany, Austria).

Furthermore, since GDCR is right the week before SoCraTes Linz, I'd expect people like Paul to have an "either GDCR or SoCraTes" mentality, tending towards SoCraTes.

So, signs are summing up that we skip it. Any counter arguments?

**Comment by ernst-fastl** [comment]
I am fine with skipping it this year. Lets focus on getting more people to the regular Dojos then.

**Comment by codecop** [comment]
The number of participants is not the "thing". We could ask on the Softwerkskammer mailinglist Wien if someone wants to host the CR. It does not have to be big. Maybe a small company wants to step up? What do you think? If yes, I will write the message then.

**Comment by ernst-fastl** [comment]
I am fine either way. My offer to facilitate still stands. It sounds like fun to visit a different company.

**Comment by dertseha** [comment]
Behrang Dadsetan wants to host a coding dojo at hitbox.tv, they are in the 2nd district. He mentioned this at the last dojo and now sent me a mail, with his boss included.

With September already taken with the Dart group, do we want to confront them with
a) the GDCR 
b) postpone them till November
c) no GDCR and do a "regular" dojo there in October?

Other than that, OK, we can ask around if someone wants to host (and possibly facilitate).

**Comment by codecop** [comment]
Yes you could softly offer them to host the GDCR, but they will need a lot of help there. Also it is ok to decline because of unknowns, work involved, etc.
And yes c) is definitely an option as the fate of GDCR is unsure.

**Comment by dertseha** [comment]
Today I'll have another talk with my boss where I'll tell about our newest stance. Let's see how much they want to host the GDCR now.

**Comment by dertseha** [comment]
That talk was cancelled, I'll try to get hold of my boss tomorrow.

**Comment by dertseha** [comment]
All right. FRQ did not demand to host another coderetreat this year and I also doubt hitbox will want to do it. I offered them now to host a regular dojo in October.

Unless something/someone comes up to pull this through during September, we're not doing a GDCR for Vienna. Closing for now.

**Comment by codecop** [comment]
Just to inform you. Techtalk volunteered to host the CR and Paul is the host and did already a lot of work.
* Coderetreat Event: http://coderetreat.org/events/global-day-of-coderetreat-2016-vienna-austria
* SWK event: https://www.softwerkskammer.org/activities/gdcr16-wien - invitation has been sent.
* Registration: https://www.eventbrite.de/e/global-day-of-coderetreat-2016-vienna-austria-22-october-2016-tickets-28042883018

This is kind of last minute surprise. There should not be much work for us here besides spreading the word.

The following user groups have been informed: SWK, Scala, BDD, F#, Clojure, PHP, Dart, Functional, Ruby.

Currently I am looking for an outside facilitator because TechTalk offers money for that.

**Comment by codecop** [comment]
@paulroho to join the discussion

**Comment by paulroho** [comment]
Registrations on Eventbrite seem to be going rather well.
Great thanks to @codecop for the support around making it a great event. I hope to be able to welcome many of the all-time dojers of the Vienna region.
Please don't forget to advertise among your peers (meetups, colleagues, friends, ...).
Looking forward!

**Comment by dertseha** [comment]
@ernst-fastl and @mlem - They are now looking for a facilitator. Are you still interested in doing it for @paulroho ?
(I already made other plans for the day, so it's another coderetreat without me)

**Comment by codecop** [comment]
No worries. An international facilitator was found (so we can participate and learn from him in two ways). Everything is set. We are good to go.

**Comment by ernst-fastl** [comment]
I signed up as a participant, but if help is needed with regards to facilitation I am happy to help.

**Comment by paulroho** [comment]
@ernst-fastl: Thank you for offering help, appreciate that. But currently things seem to be settled.

**Comment by codecop** [comment]
GDCR was a success. All went well. Closing issue.
